# Generated by Django 2.2.3 on 2019-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('edep', models.CharField(max_length=200)),
                ('ecode', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
